<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'linux技术222',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2018/0502/20180502053201305.jpeg',
    'keywords' => '技术',
    'description' => 'linux技术222',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1525253153',
    'updatetime' => '1525420117',
    'hitsid' => 'c-1-2',
    'views' => '12',
    'yesterdayviews' => '3',
    'dayviews' => '3',
    'weekviews' => '12',
    'monthviews' => '12',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'linux技术',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2018/0502/20180502053530152.png',
    'keywords' => '技术',
    'description' => 'linux技术',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1525253089',
    'updatetime' => '1525420119',
    'hitsid' => 'c-1-1',
    'views' => '6',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
);
?>